
# Autostart processes
# Example autostarts:
# exec-once = $terminal
# exec-once = nm-applet
# exec-once = kitty & wofi

# System utilities
 # chatgpt says that kwalletd6 is the reason i can never ever connect to wifi but i clearly need to do my own research cause chatgpt sucks lmao
 # for reference when i couldnt mount my windows drive properly when i first started using arch, chatgpt hallucinated that i had to do some wild chroot stuff and put the boot in uefi mode, which it gathered by making me look for a directory that wouldnt exist either way?? the actual answer was that secure boot turned itself back on or something like that cause i am SURE i had already turned it off before. whatever. what am i even saying this is a config file.
 # current wifi bandaid: run nm-connection-editor, open wifi settings > wifi security, click icon on password box, select "set for all users"
# exec-once = /usr/libexec/kf4/polkit-kde-authentication-agent-1
 # ^ kde polkit location if polkitd is slacking off
exec-once = $panel & $menu & $wallpaper & $notif
