
# This is the main configuration file that Hyprland runs when it boots.
# Refer to the wiki for more information and a full list of configurable options.
# https://wiki.hyprland.org/Configuring/

# imports
source = shared-hyprland/vars.conf # shared variables
source = shared-hyprland/input.conf # keyboard and mouse configuration
source = shared-hyprland/keybinds.conf # hyprland keybinds
source = shared-hyprland/decoration.conf # window look and feel
source = shared-hyprland/autostart.conf # startup apps
source = plugins.conf # hyprpm plugin configuration


# https://wiki.hyprland.org/Configuring/Monitors/
monitor=smasnug-front,preferred@144,auto,auto


###################
### LOOK & FEEL ###
###################

# https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
}

############################
### WINDOWS & WORKSPACES ###
############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/
#     https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
