
# This is the main configuration file that Hyprland runs when it boots.
# Refer to the wiki for more information and a full list of configurable options.
# https://wiki.hyprland.org/Configuring/

# imports
source = vars.conf # shared variables
source = input.conf # keyboard and mouse configuration
source = keybinds.conf # hyprland keybinds
source = decoration.conf # window look and feel
source = autostart.conf # startup apps
source = plugins.conf # hyprpm plugin configuration


# https://wiki.hyprland.org/Configuring/Monitors/
monitor=smasnug-front,preferred@144,auto,auto


###################
### LOOK & FEEL ###
###################

# https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
}

############################
### WINDOWS & WORKSPACES ###
############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/
#     https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = true
    match:pin = true

    no_focus = true
}
