
# modified version of default hyprland config

# This is the main Hyprland configuration file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# For a full list of configurable options, see the wiki.

# You can split this configuration into multiple files.
# Create or find a separate file and link them to this file like so:
source = shared-hyprland/vars.conf
source = shared-hyprland/input.conf
source = shared-hyprland/keybinds.conf
source = plugins.conf


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=SamsungFrnt,preferred@144,auto,auto


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


####################
### STARTUP APPS ###
####################

source = ~/.config/hypr/shared-hyprland/autostart.conf


###################
### LOOK & FEEL ###
###################

source = ~/.config/hypr/shared-hyprland/decoration.conf

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

############################
### WINDOWS & WORKSPACES ###
############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
