
# This file contains variables used by various config files located in ~/.config/hypr/ and ~/.config/waybar/
# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty # kitty is installed by default on Hyprland and I prefer it.
$panel = waybar
$menu = /usr/bin/rofi -show drun # im sure the fact that arch wants the EXACT path of SPECIFICALLY rofi is a great sign and has absolutely nothing to do with the horrible mess that is my dbus configuration dont look over there
$screenshot = hyprshot -o "~/Pictures/Screenshots"
$fileManager = thunar
$browser = flatpak run one.ablaze.floorp

# decoration vars

$rounding = 4 # how round the corners of windows and waybar modules are
$borderSize = 2 # how thick the borders of windows and waybar modules are

# colors

$deacBorder = rgba(595959aa)
$deacFill = rgba(00000000)
