
# This file contains variables used by various config files located in ~/.config/hypr/ and ~/.config/waybar/
# See https://wiki.hypr.land/Configuring/Keywords/

# applications/daemons

$terminal = kitty # kitty is also installed by default on Hyprland
$panel = waybar
$menu = rofi -show drun # im sure the fact that arch wants the EXACT path of SPECIFICALLY rofi is a great sign
$screenshot = grim -g "$(slurp)" | wl-copy
$fileManager = thunar
$browser = flatpak run one.ablaze.floorp
$wallpaper = swaybg -i "/home/tabtray/Wallpapers/niko-wallpapy-2.jpg" -m fit
$notif = dunst

# colors

$deacBorder = rgba(595959aa)
$deacFill = rgba(00000000)
