
# Autostart processes (ex. notifications daemons, status bars, flatpak apps, etc.)
# Example autostarts:
# exec-once = $terminal
# exec-once = nm-applet
# exec-once = kitty & wofi

# System utilities
exec-once = /usr/libexec/kf4/polkit-kde-authentication-agent-1
exec-once = $panel & $menu & hyprpaper
