
# This config file handles input type and mouse sensitivity.

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = -0.45  # -1.0 - 1.0, 0 means no modification.
    scroll_factor = 3.5 # the default scroll factor, repeat rate, and repeat delay are abysmal git help me

    repeat_rate = 30
    repeat_delay = 350

    touchpad {
        natural_scroll = false
    }
}

# More info:
# Gestures (eg. swipe gestures) https://wiki.hypr.land/Configuring/Variables/#gestures
# Per-device configs https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs
