
# This config file handles keyboard keybinds.

# See https://wiki.hypr.land/Configuring/Keywords/

$metaMod = SUPER  # Sets "Windows" key as a modifier for some keybinds.
$altMod = ALT  # Sets "Alt" key as a modifier for some keybinds

# See https://wiki.hypr.land/Configuring/Binds/ for more.
bind = $metaMod, T, exec, $terminal
bind = $metaMod, Q, killactive,
bind = $metaMod, M, exit,
bind = SUPER, SUPER_L, exec, $menu # boy why you so needlessly complicated
bind = $metaMod, F, exec, $fileManager
bind = $metaMod, B, exec, $browser
bind = $metaMod, V, togglefloating,
# bind = $altMod, P, pseudo, # dwindle
bind = $altMod, J, togglesplit, # dwindle

# Move window focus with metaMod + arrow keys
bind = $metaMod, left, movefocus, l
bind = $metaMod, right, movefocus, r
bind = $metaMod, up, movefocus, u
bind = $metaMod, down, movefocus, d

# Switch workspaces with META + [0-9]
bind = $metaMod, 1, workspace, 1
bind = $metaMod, 2, workspace, 2
bind = $metaMod, 3, workspace, 3
bind = $metaMod, 4, workspace, 4
bind = $metaMod, 5, workspace, 5
bind = $metaMod, 6, workspace, 6
bind = $metaMod, 7, workspace, 7
bind = $metaMod, 8, workspace, 8
bind = $metaMod, 9, workspace, 9
bind = $metaMod, 0, workspace, 10

# Move active window to a workspace with META + SHIFT + [0-9]
bind = $metaMod SHIFT, 1, movetoworkspace, 1
bind = $metaMod SHIFT, 2, movetoworkspace, 2
bind = $metaMod SHIFT, 3, movetoworkspace, 3
bind = $metaMod SHIFT, 4, movetoworkspace, 4
bind = $metaMod SHIFT, 5, movetoworkspace, 5
bind = $metaMod SHIFT, 6, movetoworkspace, 6
bind = $metaMod SHIFT, 7, movetoworkspace, 7
bind = $metaMod SHIFT, 8, movetoworkspace, 8
bind = $metaMod SHIFT, 9, movetoworkspace, 9
bind = $metaMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
# bind = $metaMod, G, togglespecialworkspace, magic
# bind = $metaMod SHIFT, G, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $metaMod, mouse_down, workspace, e+1
bind = $metaMod, mouse_up, workspace, e-1

# Move/resize windows with ALT + LMB/RMB and dragging
bindm = $altMod, mouse:272, movewindow
bindm = $altMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Use vars.conf defined screenshot tool in region mode with META + SHIFT + S
bind = $metaMod SHIFT, S, exec, $screenshot, -m region
