
# This config file contains all the variables used in hyprland.conf and other config files located in ~/.config/hypr
# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty # Ptyxis is the default terminal emulator for Bazzite, kitty is the one Hyprland reccomends.
$panel = hyprpanel
$menu = rofi -show drun
$screenshot = hyprshot -o "~/Pictures/Screenshots"
$fileManager = dolphin
$browser = flatpak run one.ablaze.floorp
