
# This config file contains all the variables used in hyprland.conf and other config files located in ~/.config/hypr
# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty # kitty is installed by default on Hyprland and I prefer it.
$panel = waybar
$menu = /usr/bin/rofi -show drun # why does arch want the exact path? Who TF Knows !!11
$screenshot = hyprshot -o "~/Pictures/Screenshots"
$fileManager = dolphin # Use thunar if dolphin decides to be dumb again.
$browser = flatpak run one.ablaze.floorp
